name: offensive-security-on-loadbalancer

# Ce scénario reflète notre environnement de production : un serveur Nginx utilisé
# comme load balancer pour les réplicas de notre application. 
# Juste à côté, un service Fail2Ban surveille en quasi temps réel les logs générés,
# constituant ainsi une première ligne de défense contre les menaces potentielles.  

services:
  

  ########################################
  ############ INIT APP ########

  app:
    image: maissacrement/pock8snodejs
    deploy:
      replicas: 2
    networks:
      - infra


networks:
  infra:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.30.0/24
          gateway: 172.100.30.1

  internet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.40.0/24
          gateway: 172.100.40.1

volumes:
  nglog:
