global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']   # the cadvisor for docker

  - job_name: 'node'
    static_configs:
      - targets: ['exporter:9100']   # the node-exporter for complete sys

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginxexporter:9113']   # the node-exporter for complete sys

  - job_name: 'netanalyser'
    static_configs:
      - targets: ['exporternetanalyser:8000']   # the node-exporter for complete sys