name: Docker Image CI

on:
  push:
    branches: [ "main" ] # l'action s'execute a chaque push sur main
  pull_request:
    branches: [ "main" ] # l'action s'execute a chaque pull request sur main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Made SAST docker running catainer analysis
      run: |
        make running-container-analisis 2>/dev/null # la commande est sensé marché pour tout utilisateur present dans la racine du projet
        cat ./rapport/running-container-vuln.txt
    - name: Made SAST docker-compose file analysis
      run: |
        make run-project-analysis 2>/dev/null # la commande est sensé marché pour tout utilisateur present dans la racine du projet
        cat ./rapport/docker-compose-images-vuln.txt
    - name: Try to compile attacker
      run: docker build . --file ./docker/Dockerfile.attack --tag attacker:$(date +%s) # On construit l'image pour savoir si elle, se construit de la meme façon sur une autre machine
